name: Node CI

on:
  - push

env:
  CI: true

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Print workflow's name
        run: echo "run $GITHUB_WORKFLOW"
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
      - name: Install npm packages
        run: npm ci
      - name: Run lint
        run: npm run lint
      - name: Run tests
        run: make test
      - name: Print Hellow from hexlet
        uses: hexlet-components/hello-from-hexlet-action@release
